<?php
/**
 * @package RoomworksBusinessNetworking
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class RBN_Activator {

	public static function activate() {
		RBN_Schema::install();
		RBN_Capabilities::add_caps();

		// Registered here too (not just on init) so the rewrite rules
		// generated by flush_rewrite_rules() below already know about them.
		RBN_Taxonomy_Business_Category::register();
		RBN_Taxonomy_Service::register();
		RBN_Post_Type_Business::register();
		RBN_Post_Type_Job::register();

		RBN_Taxonomy_Business_Category::seed_defaults();
		RBN_Countries::seed_defaults();

		flush_rewrite_rules();
	}
}
